slack_webhook: TQJ9F14QJ/B011B5RKVGF/Ui5eDbMk13szKU7U5x0ew9XX
mail_sender: aegiacometti@hotmail.com
mail_username: aegiacometti@hotmail.com
mail_password: M41l.hotmail
github_userid: aegiacometti
github_password: Adr.04gia