# ansible-playbook netconf-backup.yml -i ./hosts
# -f #forks (optional) means the # of processes to execute in parallel.
# -l xxx limit the playbook to the specified hosts
#
---
- name: Network configuration backup - IOS ASA NxOS EOS F5
  hosts: all
  gather_facts: false

  # Set following variables
  vars:
    backup_dir: "./backups"
    keep_local_history: "yes"
    historic_files_to_keep: 10

    alert_slack: "no"

    alert_mail: "no"
    mail_host: smtp.xxx.com
    mail_port: 587
    mail_to: support@xxx.com

    github_backup: "no"
    git_local_repository: "{{ backup_dir }}/github-staging"
    # For the remote repository do not use the FQDN.
    #  Example:
    #    for "https://github.com/aegiacometti/backups.git"
    #    use: git_remote_repository: "/aegiacometti/backups.git"
    git_remote_repository: "/xxx/yyy.git"
    git_branch: master

    clean_patterns:
    - "\\A[^!]*"
    - "ntp clock-period..."
    - "! Last configuration change..."

  # Comment/delete the tasks of the platform that you are not interested in backing up the device configuration files
  tasks:
    - name: Cisco IOS
      connection: network_cli
      import_tasks: playbooks/netconf-backup-ios.yml
      when: platform == 'ios'

    - name: Cisco NxOS
      connection: network_cli
      import_tasks: playbooks/netconf-backup-ios.yml
      when: platform == 'nxos'

    - name: Cisco ASA
      connection: network_cli
      import_tasks: playbooks/netconf-backup-asa.yml
      when: platform == 'asa'

    - name: Arista
      connection: network_cli
      import_tasks: playbooks/netconf-backup-asa.yml
      when: platform == 'eos'

    - name: F5
      import_tasks: playbooks/netconf-backup-f5.yml
      when: platform == 'f5'

    - name: Push configuration changes to GitHub
      import_tasks: playbooks/netconf-backup-git-sync.yml
      when: github_backup == 'yes'
      run_once: true

    - name: Send executed backup notification to Slack
      vars:
        step: "finished"
      import_tasks: playbooks/netconf-backup-msg-slack.yml
      when: alert_slack == "yes"
      run_once: true

    - name: Send executed backup notification by email
      vars:
        step: "finished"
      import_tasks: playbooks/netconf-backup-send-mail.yml
      when: alert_mail == "yes"
      run_once: true
