- name: GitHub - Get timestamp
  shell: date
  register: timestamp
  delegate_to: localhost

- name: GitHub - Make sure we're in the right branch
  shell: git checkout {{git_branch|default('master')}}
  args:
    chdir: "{{ git_local_repository }}"
  delegate_to: localhost

- name: GitHub - Pull remote changes
  shell: git pull https://{{github_userid}}:{{github_password}}@github.com{{git_remote_repository}}
  args:
    chdir: "{{ git_local_repository }}"
  delegate_to: localhost

- name: GitHub - Check the directory status
  shell: git status
  args:
    chdir: "{{ git_local_repository }}"
  register: changes
  delegate_to: localhost

- name: GitHub - Add files, commit, and push to GitHub
  shell: |
    git add .
    git commit -m "Configuration changed on {{ timestamp.stdout }}"
    git push https://{{github_userid}}:{{github_password}}@github.com{{git_remote_repository}}
  args:
    chdir: "{{ git_local_repository }}"
  when: not("working directory clean" in changes.stdout)
  delegate_to: localhost